### PR TITLE
Torrents!

### LINKED ISSUE #35: Torrent feature
Torrent feature would be dope, just not to bash the single server and be more responsible
I think .torrent files in target location would be enough to simplify this

### PR DESCRIPTION
**Pull request by jojo2357**
closes #35

Changelog:

 * Fix index corrupted bug
 * add torrenting instead of forcing http update
 * Fix octal update

### CODE REVIEW

**Comment by jojo2357** [comment]
Does purging work as intended? Right now iirc t mode does no such thing, but the standard version does still purge. This could be a problem, or if the user is advanced enough we hope they know whether or not they want to keep old versions.

**Comment by Jaifroid** [comment]
> Does purging work as intended? Right now iirc t mode does no such thing, but the standard version does still purge. This could be a problem, or if the user is advanced enough we hope they know whether or not they want to keep old versions.

-t mode doesn't understand -p (and I think that's correct, -t mode should never purge, and so -p is redundant). I'm going on having done a dry-run with and without -p and noticing that the outcome would have been the same, and different from doing the same without -t. But in terms of a "live run", I ran it with -p. I didn't quite dare run it without, even though the dry-run had indicated it would be safe! I have a lot of old ZIMs I use for testing / development on Kiwix, and I don't want to lose them. So I would strongly urge against introducing a purge function in -t mode.

**Review by Jaifroid — APPROVED** [review]
I can't review the code, but I've reviewed through testing, and agree with the proposed functionality. I've also reviewed the README. Thank you for this great PR!

**Review by DocDrydenn — APPROVED** [review]
Hello all!

Just wanted to give a quick update. My homelab has been undergoing upgrades (racking changes, storage upgrades, and a full network overhaul) for about the last two weeks... and I've been unable to physically test the scrip updates against my ZIM library.

That said, I don't let me be the reason this merge gets held up. I gave the changes a look and didn't see anything that looks to be a problem. Knowing that you all have tested, I say Go.

**Comment by jojo2357** [comment]
Well we have the `-d` flag for a reason!

**Pull request merged**
